name: Build and deploy container app to Azure Web App - hatespeech-flask

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://hatespeechinstance.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}
          password: ${{ secrets.AzureAppService_ContainerPassword_2aa58e38663d45df8d30765ed32ad4c9 }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images with Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: List images
        run: docker images

      - name: Tag and Push app1 Docker image
        run: |
          docker tag hello_world_flask_app1:latest hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app1:${{ github.sha }}
          docker push hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app1:${{ github.sha }}

      - name: Tag and Push app2 Docker image
        run: |
          docker tag hello_world_flask_app2:latest hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app2:${{ github.sha }}
          docker push hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app2:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hatespeech-flask"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e08c332857a14f84bc7e8db2ab715171 }}
          images: "hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app1:${{ github.sha }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp2
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hatespeech-flask"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e08c332857a14f84bc7e8db2ab715171 }}
          images: "hatespeechinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_21f0839a5c084350921d3447b3afcf3d }}/hatespeechinstance/hello-world-flask-app2:${{ github.sha }}"
